[globals]

storage_folder = "data_2"
runner_persistence = "data_2/runner_persistence.json"

[components]
# Main component, source loads the data from the csv file (after parsing, it deletes the file), whenever a new
# file is added, it will be loaded as well. This allows us to have a stream of data.
[components.source]

multiple_outputs = true
class = "components.source.SourceComponent"
per_train = true
run_per_train = false
source = "in/ar41.csv"


[components.enriched]

class = "components.preprocess.data_enriching.DataEnrichingComponent"
dependencies = [
    { component = "source", batch_size = 10_000 }
]
run_per_train = false # No need to have per train, add data per row


[components.chainsawed]

class = "components.preprocess.chainsaw_processing.ChainsawProcessing"
dependencies = [
    { component = "enriched", batch_size = 1000 }
]
run_per_train = true
per_train = true
outliers_producer = true
intensity_column = "intensity"


[components.surgery]

class = "components.preprocess.surgeon_processing.SurgeonProcessing"
dependencies = [
    { component = "enriched", batch_size = 200 },
    { component = "enriched", batch_size = 200, before = true }
]
run_per_train = true
per_train = true


[components.train_too_fast]

class = "components.sensors.speed.TrainTooFastComponent"
dependencies = [
    { component = "surgery", batch_size = 200 }
]
run_per_train = true
per_train = true
outliers_producer = true

[components.fluid_temperature]

class = "components.sensors.fluid_temperature.FluidOverheatingComponent"
dependencies = [
    { component = "chainsawed", batch_size = 200 }
]
run_per_train = true
per_train = true
outliers_producer = true

[components.rpm_and_oil]

class = "components.sensors.rpm_and_oil.OilPressureNotMatchingRPMsComponent"
dependencies = [
    { component = "chainsawed", batch_size = 200 }
]
run_per_train = true
per_train = true
outliers_producer = true

[components.dbscan]

class = "components.general.dbscan.DBScanOutliers"
dependencies = [
    { component = "source", batch_size = 10_000 }
]
run_per_train = false
per_train = true
outliers_producer = true


[components.kmeans]

class = "components.general.kmeans.KMeansOutliers"
dependencies = [
    { component = "source", batch_size = 10_000 }
]
run_per_train = false
per_train = true
outliers_producer = true


[components.ma_outliers]

class = "components.general.moving_average.MovingAverageOutlierDetector"
dependencies = [
    { component = "source", batch_size = 10_000 }
]
run_per_train = false
per_train = true
outliers_producer = true

[components.na]

class = "components.general.na_values.NotApplicableCountComponent"
dependencies = [
    { component = "source", batch_size = 10_000 }
]
run_per_train = false
per_train = true
outliers_producer = true


