[components]

[components.source]

multiple_outputs = true
class = "components.source.SourceComponent"
per_train = true
run_per_train = false
source = "in/ar41.csv"

[components.airtemp_1]

class = "components.moving_average_outliers.MovingAverageOutlierDetector"
dependencies = [
    { component = "source", batch_size = 100 }
]

window = 10
column = "air_temp_1"
sensitivity = 3


