[globals]

storage_folder = "data_2"
runner_persistence = "data_2/runner_persistence.json"

[components]

[components.source]

multiple_outputs = true
class = "components.source.SourceComponent"
per_train = true
run_per_train = false
source = "in/ar41.csv"


[components.random_forest_outliers]

class = "components.random_forest.RandomForestOutliers"
dependencies = [
    { component = "source", frequency = "1d" },
]
y = "water_temp_1"
X = ["air_temp_1", "air_temp_2", "oil_temp_1", "oil_temp_2", "rpm_1", "rpm_2"]
run_per_train = true

[components.prophet_outliers]

class = "components.prophet.ProphetOutliers"
dependencies = [
    { component = "source", frequency = "7d" },
    { component = "source", frequency = "30d", before = true }
]
y = "air_temp_1"
run_per_train = false


